### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by leroycep** [Geemili/time-tracker#11]
In all honesty, I'm not sure when or if `augr` can be considered "ready", as it's mostly a hobby project of mine.

That said, here are some of the things I want to accomplish.

### Platforms

I want `augr` to run everywhere, and sync data in the most convenient method for the user.

- Frontends
  - [ ] Command Line Interface
     - [x] Linux
     - [x] Android
     - [ ] Windows (does it run on windows?)
     - [ ] Mac OSX
  - [ ] Gtk App
     - [ ] Desktop
     - [ ] Librem 5
  - [ ] Web App (for browsers everywhere)
- Sync Methods
  - [x] Syncthing
  - [ ] Personal server running an `augr` daemon?
  - [ ] Paid `augr` service for multiple users?

### Features

What features are required before the `augr` is considered 1.0?

- Reporting
  - Flexible method of generating reports and charts
- Better editing interface
- Importing and Exporting data
  - Timewarrior
  - Toggl

### Tests

What verifications should be done before the `augr` is considered 1.0?

- Unit tests
- Fuzz tests

## Final Words

This list is incomplete and probably too ambitious for a hobby project. Expect it to be changed a lot.

**Comment by memchk** [comment]
I can confirm it runs on windows, and displays nicely in powershell.
